# Generated by Django 5.0.7 on 2024-08-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='author',
        ),
    ]
